# Generated by Django 5.2.11 on 2026-02-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.PositiveIntegerField(help_text='Percentage (0-100) or Fixed Amount in INR')),
                ('min_purchase_amount', models.PositiveIntegerField(default=0, help_text='Minimum cart value in INR')),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='Maximum discount for percentage type', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total usage limit', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_inr', models.PositiveIntegerField()),
                ('service_duration', models.CharField(help_text='e.g., 1 Day, 2-3 Days, 1 Week', max_length=100)),
                ('includes', models.TextField(help_text='What is included in this package')),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('beginner_setup', 'Full Balcony/Terrace Gardening Setup (Beginners)'), ('kit_support', 'Kit Setup Support (Existing Customers)'), ('corporate_gifting', 'Corporate Gifting Consultation'), ('custom', 'Custom Garden Project')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon'),
        ),
    ]
