# Generated by Django 4.2.8 on 2026-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon_servicepackage_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('price_inr', models.PositiveIntegerField()),
                ('savings_percentage', models.PositiveIntegerField(default=0)),
                ('services_json', models.JSONField(default=list, help_text='List of services with frequency')),
                ('visit_frequency', models.CharField(max_length=100)),
                ('response_time', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'price_inr'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(help_text='e.g., A1, C2, M3', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('residential', 'Residential Solutions'), ('corporate', 'Corporate Solutions'), ('institutional', 'Institutional & Government'), ('maintenance', 'Maintenance Plans'), ('digital', 'Digital Services'), ('workshop', 'Workshops & Events'), ('combo', 'Combination Packages'), ('custom', 'Custom Solutions')], max_length=20)),
                ('price_inr', models.PositiveIntegerField()),
                ('price_max_inr', models.PositiveIntegerField(blank=True, help_text='For price ranges', null=True)),
                ('space_coverage', models.CharField(blank=True, max_length=100)),
                ('setup_time', models.CharField(blank=True, max_length=100)),
                ('warranty', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('includes_json', models.JSONField(default=list, help_text='List of included items with specifications')),
                ('suitable_plants', models.TextField(blank=True)),
                ('ideal_for', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'price_inr'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('hobby', 'Hobby Workshop'), ('corporate', 'Corporate Workshop')], max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('price_per_person', models.PositiveIntegerField()),
                ('min_group_size', models.PositiveIntegerField(default=1)),
                ('max_group_size', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('includes', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='area_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='budget',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
