# Generated by Django 4.2.8 on 2026-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_maintenanceplan_serviceplan_workshopevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., Unsplash)', max_length=500, null=True),
        ),
    ]
